name: amlmm
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda==2.2.1
  - ipykernel  
  - pip:
    - prompt-toolkit==2.0.7
    - azure-cli==2.0.51
    - azure==4.0.0
    - azureml-sdk==1.0.2
 

