name: amlmm
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.1.0
  - ipykernel  
  - pip:
    - prompt-toolkit==2.0.7
    - azure-cli==2.0.53    
    - azureml-sdk==1.0.2
