name: amlmm
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - nb_conda_kernels
  - ipykernel
  - tornado<6
  - urllib3
  - pip
  - pip:
    - azure-cli
    - azureml-sdk[notebooks]
    - azure-storage-blob==12.0.0
    - nbconvert
    - papermill
    - prompt-toolkit
    - python-dotenv
